# -*- coding: utf-8 -*-
"""pertemuan1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Itf_V12D11AhVZo9fLxHsekNWaIMIfGt
"""

x = 562
y = 743
z = x+y
print(z)

i = "K"
print(i)

j = "Yahaloo!!"
print(j)

m = "Yahallo,"
n = "minna!!"
print(m+n)

a = True
b = True
print (a and b)

a = True
b = False
print(a and b)

a = False
b = True
print(a and b)

a = False
b = False
print(a and b)

a = 73
b = 52
print(a+b)

print(a-b)

print(b*2)

print(a/12)

print(a//12)

print(a%12)

print(5**3)

w = "Ayano-kun"
print("Yahallo, "+3*w)

a = 10
b = 4
print(a&b)

a = 10
b = 4
print(a|b)

a = 29
b = 16
a+=b
print(a)