# -*- coding: utf-8 -*-
"""string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1siOlmu11twW-cvwJX_CvuKEYuqzyGSZ5
"""

# Use quotation marks for defining string
"Michael Jackson"

# Use single quotation marks for defining string
"Michael Jackson"

# Digitals and spaces in string
' 1 2 3 4 5 6 '

# Special characters in string
'@#2_#]&*^%$'

# Print the string
print("Hello!")

# Assign string to variable
Name = "Michael Jackson"
Name

# Print the last element in the string
print(Name[-1])

# Print the first element in the string
print(Name[-15])

# Print the length of string
len("Michael Jackson")

# Take the slice on variable
Name[0:4]

# Take the slice on variable
Name[8:12]

# Get every second element. The element on index 1,3,5,...
Name [::2]

# Get every second element in the range from index 0 to 4
Name[0:5:2]

# New line escape sequence
print("Michael Jackson \n is the best")

# Tab escape sequence
print("Michael Jackson \t is the best")

# Include back slash is string
print("Michael Jackson \\ is the best")

# r will tell python that string
print(r"Michael Jackson \ is the best")