# -*- coding: utf-8 -*-
"""UAS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FX40-T5VGgS7IzZeu8KlqYT2uxrgXdEZ
"""

class Person:
    def warna_kulit(self):
      print("warna kulit : Putih")

    def warna_rambut(self):
      print("warna rambut : Hitam")

    def warna_mata(self):
      print("warna mata : Biru")

    def tinggi_badan(self):
      print("tinggi badan : 170")

    def berat_badan(self):
      print("berat badan : 50")

obj_warna_kulit = Person()
obj_warna_rambut = Person()
obj_warna_mata = Person()
obj_tinggi_badan = Person()
obj_berat_badan = Person()
for Person in (obj_warna_kulit, obj_warna_rambut, obj_warna_mata, obj_tinggi_badan, obj_berat_badan):
  Person.warna_kulit()
  Person.warna_rambut()
  Person.warna_mata()
  Person.tinggi_badan()
  Person.berat_badan()

def fact(n):
  result = n
  for i in range(1,n):
    result *= i
  return result

print (fact(10))

def charger(x, y):
    x = 2
    y[0] = 'spam'
  
X = 1
Y = [1, 2]
#charger(X, L)
#print (X, L)

L = [1, 2]
charger(X, L[:])

print (X, L)

def minmax(test, *args):
  res = args[0]
  for arg in args[1:]:
    if test(arg, res):
      res = arg
  return res

def lessthan(x, y): return x < y
def grtrthan(x, y): return x > y

print (minmax(lessthan, 4, 2, 1, 5, 6, 3))
print (minmax(grtrthan, 4, 2, 1, 5, 6, 3))

class India():
  def capital(self):
    print("New Delhi is the capital of India.")

  def language(self):
    print("Hindi is the most widely spoken language of India.")

  def type(self):
    print("India is a developing country.")

class USA():
  def capital(self):
    print("Washington, D.C is the capital of USA.")

  def language(self):
    print("English is the primary language of USA.")

  def type(self):
    print("USA is a developed country.")

obj_ind = India()
obj_usa = USA()
for country in (obj_ind, obj_usa):
  country.capital()
  country.language()
  country.type()

class Bird:
  def intro(self):
    print("There are many types of birds.")

  def flight(self):
    print("Most of the birds can fly but some cannot.")

class sparrow(Bird):
  def flight(self):
    print("Sparrows can fly.")

class ostrich(Bird):
  def flight(self):
    print("Ostriches cannot fly.")

obj_bird = Bird()
obj_spr = sparrow()
obj_ost = ostrich()

obj_bird.intro()
obj_bird.flight()

obj_spr.intro()
obj_spr.flight()

obj_ost.intro()
obj_ost.flight()